### ISSUE TITLE
Развернуть копию базы на сервере 

### ISSUE THREAD

**Issue by sergere15** [sergere15/analysis_of_SBPU_timetable#12]
Развернуть имеющуюся базу и средства для работы с ней(MS sql server)

**Comment by sncodeGit** [comment]
База данных timetable-live на сервере была развернута. Использован SQL Server 2017 developer edition. 
Подключение возможно через localhost в соответствии с режимом проверки подлинности Windows: https://docs.microsoft.com/ru-ru/dotnet/framework/data/adonet/sql/authentication-in-sql-server
Для удобства был установлен Microsoft SQL Server Management Studio (SSMS).

**Comment by sncodeGit** [comment]
Открывать доступ для внешних подключений к бд смысла не вижу в связи с последующей настройкой ELK на том же сервере.
При необходимости в рамках этой же задачи можно открыть.
