### ISSUE TITLE
Выгрузить данные из базы в ES на сервере

### ISSUE THREAD

**Issue by sergere15** [sergere15/analysis_of_SBPU_timetable#15]
Выгрузить из копии базы нужную информацию в Elastic Search на сервере.

**Comment by sncodeGit** [comment]
Подправил подключение к LS пользователя БД. На данный момент возникает ошибка 'block in start input'. Вероятно, она связана с некорректной работой JDBC. С проблемой разбираемся.
Напоминаю команду для подключения конфигурационного файлй sql.conf:
`.\bin\logstash.bat -f .\sql.conf`. 
Выполнять её необходимо из директории `C:\ELK\logstash-7.5.0\logstash-7.5.0`

**Comment by sncodeGit** [comment]
Для корректного отображения ошибок в cmd нужно изменить кодировку на UTF-8:
`chcp 65001`

**Comment by sncodeGit** [comment]
Также обращаю внимание на то, что logstash работает в паре c elasticsearch, соответственно, перед загрузкой данных в logstash необходимо запустить elasticsearch, т.е. выполнить скрипт:
`C:\ELK\elasticsearch-7.5.0\bin\elasticsearch.bat`

**Comment by sncodeGit** [comment]
Ошибку, возникающую при выполнения запроса в logstash решили, сейчас выгрузка данных в процессе выполнения.

**Comment by Lossfull** [comment]
Данные успешно выгружены
