### ISSUE TITLE
Удаленное подключение к серверу.

### ISSUE THREAD

**Issue by sergere15** [sergere15/analysis_of_SBPU_timetable#17]
Настроить удаленное подключение к сенрверу, для получения доступа к ES/Kibana. Чтобы была возможность подлючиться с компьютеров той же сети. Быть может и за пределеми, но это усложняет задачу и снижает безопасноть.

**Comment by sncodeGit** [comment]
В теории подключение именно к Kibana должно работать по ссылке:
`http://IP:5601`
`IP` - IP-адрес сервера
`5601` - порт подключения к Kibana
Пока смотрим, как это работает в данном случае.

**Comment by sncodeGit** [comment]
Произведены следующие действия:
1) Соответствующим образом изменены настройки брандмауэра Windows
2) Изменён конфигурационный файл Kibana `C:\ELK\kibana-7.5.0-windows-x86_64\config\kibana.yml`. Его текущая версия расположена в папке Back-end.

Теперь доступ к Kibana может быть осуществлён с помощью перехода по следующему URL-адресу `http://192.168.148.17:5601` с любого компьютера, подключённого к частной сети, VPN-доступ которой нам предоставили в рамках проекта.
Иными словами, при включённом подключении по ключу stxxxxxx.ovpn (входить через `https://vcenter.law.spbgu/` не обязательно) достаточно перейти по указанному выше адресу.
