### ISSUE TITLE
Формирование отчета

### ISSUE THREAD

**Issue by sergere15** [sergere15/analysis_of_SBPU_timetable#18]
Сформировать все необходимые для сдачи материалы: Отчет, Проектное задание, Календарный график. В соответствии с заданными критериями.

**Comment by sergere15** [comment]
Проектное задание сформировано. Все ссылки, согласно инструкции, внесены в таблицу проектов.

**Comment by sergere15** [comment]
Был сформирован отчет, отражающий достигнутые результаты и наиболее актуальное состояние проекта.

**Comment by sncodeGit** [comment]
По итогу встречи с принимающей стороной принято решение о реструктуризации и переработке итогового отчета в соответствии со стандартами ГОСТ. Задача решается в рамках отдельного issues.
