### ISSUE TITLE
Втсречи с диспетчерами

### ISSUE THREAD

**Issue by sergere15** [sergere15/analysis_of_SBPU_timetable#2]
- [x] Неофициальная встреча
      Встреча проведена, полученная информация обсуждается.
- [x] Назначить дату официальной встречи
       18 октября, пятница
- [x] Провести саму встречу
         Встреча проведена, некоторые выводы из нее были сделаны. Вкупе с итогами встречи с заказчиком ведется пересмотр стека технологий и пересмотр основных моментов и технологий разработки.

**Comment by sergere15** [comment]
Дата официальной встречи назначена, ведуться финальные уточнения

**Comment by sergere15** [comment]
Все первоначальные встречи проведены. Скорее всего, будут проведены дополнительные встречи с диспетчерами.

**Comment by tremasov55k** [comment]
@sergere15 Добрый день! Что-то интересное удалось выяснить у диспетчеров? Стал ли процесс более прозрачным?

**Comment by sergere15** [comment]
> 
> 
> @sergere15 Добрый день! Что-то интересное удалось выяснить у диспетчеров? Стал ли процесс более прозрачным?

Добрый вечер! В ходе общения с диспетчерами удалось выяснить довольно много проблем, но многие из них были связаны с программой для составления расписания. Узнали, что нынешних ресурсов не хватает, и составление расписания без Exel файлов и бумажных носителей сейчас не представляется возможным. 

По поводу аналитических запросов, нам удалось выяснить необходимые кейсы(отражены в issues). Также были высказаны пожелания по визуальному представлению данных: наглядное отображение окна, возможность легко сопоставить номер пары и соответствующие ей предметы.
Было выяснено, что изменения отображаются сразу(во всех 3х сервисах: составление расписания, аналитика, общедоступное расписание). 

Процесс стал прозрачнее. Некоторые неизвестные ранее моменты перестали быть таковыми.

Это краткие итоги встреч.
