### ISSUE TITLE
Разработка инструкции по деплою. 

### ISSUE THREAD

**Issue by sncodeGit** [sergere15/analysis_of_SBPU_timetable#36]
Необходимо разработать инструкцию по развертке всего необходимого ПО на сервере.

**Comment by sncodeGit** [comment]
В `Documentation` файл `Инструкция по деплою стека на Windows Server.pdf`. Это сырая версия документа. Пока дорабатываем.

**Comment by sergere15** [comment]
Инструкция разработана. Заказчик с ней ознакомлен.
