### ISSUE TITLE
Реструктуризация и переработка итогового отчета

### ISSUE THREAD

**Issue by sncodeGit** [sergere15/analysis_of_SBPU_timetable#38]
Необходимо переписать отчёт в соответствии со стандартами ГОСТ.

**Comment by AliceInHunterland** [comment]
- [x] Найти ГОСТы оформления отчетов

- [x] Изучить документацию

- [x] Проанализировать имеющийся отчет и допущенные ошибки оформления

- [x] Исправить ошибки 

- [x] Провести контрольную проверку

- [x] Повторно распечатать отчет

**Comment by sncodeGit** [comment]
Отчёт доступен в корне репозитория под названием `Отчёт по учебной практике аналитика электронного расписания СПбГУ 2019` в двух форматах - pdf и docx. Осталось перепроверить и распечатать.

**Comment by sncodeGit** [comment]
Отчёт переработан и принят заказчиком
