### ISSUE TITLE
Преполагаемые аналитичексие срезы и их реализация в Kibana

### ISSUE THREAD

**Issue by sergere15** [sergere15/analysis_of_SBPU_timetable#8]
- Группа/поток
- Промежуток времени(как минимум на день/неделю)
- Номер пары
- Преподаватель 
- Предмет
- Тип аудитории(компьютерная/конференц зал и т.д.)
- Вместимость(грубо: группа/поток или большая/средняя/маленька)
- Бакалавриат/магистратура/аспирантура(?)

**Comment by sncodeGit** [comment]
На основе данных аналитических срезов требуется:
1) Сформировать конкретную спецификацию визуального отображения необходимой информации
2) Изчить подходящий для визуализации срезов функционал Kibana
3) Реализовать в Kibana на сервере отображение аналитических срезов
4) Протестировать Usability представленного решения
